// Code generated by MockGen. DO NOT EDIT.
// Source: app/repo/repo/repo.go

// Package mock_repo is a generated GoMock package.
package mock_repo

import (
	dto "car-factory/app/dto"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCarStorage is a mock of CarStorage interface.
type MockCarStorage struct {
	ctrl     *gomock.Controller
	recorder *MockCarStorageMockRecorder
}

// MockCarStorageMockRecorder is the mock recorder for MockCarStorage.
type MockCarStorageMockRecorder struct {
	mock *MockCarStorage
}

// NewMockCarStorage creates a new mock instance.
func NewMockCarStorage(ctrl *gomock.Controller) *MockCarStorage {
	mock := &MockCarStorage{ctrl: ctrl}
	mock.recorder = &MockCarStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCarStorage) EXPECT() *MockCarStorageMockRecorder {
	return m.recorder
}

// GetCar mocks base method.
func (m *MockCarStorage) GetCar(brand string) ([]dto.CarDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCar", brand)
	ret0, _ := ret[0].([]dto.CarDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCar indicates an expected call of GetCar.
func (mr *MockCarStorageMockRecorder) GetCar(brand interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCar", reflect.TypeOf((*MockCarStorage)(nil).GetCar), brand)
}

// StoreCar mocks base method.
func (m *MockCarStorage) StoreCar(car dto.CarDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreCar", car)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreCar indicates an expected call of StoreCar.
func (mr *MockCarStorageMockRecorder) StoreCar(car interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreCar", reflect.TypeOf((*MockCarStorage)(nil).StoreCar), car)
}
