version: '3.9'

services:
  #DB CONTAINER
  db:
    container_name: postgres_container
    image: postgres
    networks:
      - new
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
    volumes:
      -  postgres_db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  #MAKE MIGRATIONS
  migrate:
    image: migrate/migrate
    networks:
      - new
    #PATH TO MIGRATIONS
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "./migrations", "-database",  "postgres://postgres:qwerty@db:5432/postgres?sslmode=disable", "up" ]
    links:
      - db
  #APP CONTAINER
  api:
    build:
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    networks:
      - new
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
      ENV: ${ENV}
      HTTP_PORT: ${HTTP_PORT}
      HTTP_HOST: ${HTTP_HOST}
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  postgres_db:

networks:
  new: